name: Generate and Publish Documentation

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install  # Remplacez cette commande par la commande d'installation de vos dépendances

      - name: Build Documentation
        run: run javadoc::javadoc  # Remplacez cette commande par la commande de génération de la documentation

      - name: Deploy to gh-pages
        uses: actions-gh-pages@v3